name: Labeler
on:
  pull_request_target:
    types: [opened, synchronize]
    branches: [master]

permissions: read-all

jobs:
  labeler:
    permissions:
      pull-requests: write
    name: Auto-Label PRs
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@6704db0bcba106d07482efabbc79d3092af74fa2 # v2
