name: Disallow "On Hold" PRs
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
    branches: [master]

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@e1d7e79aa0933af1728011705a30528a279874fd # v3.1
        with:
          hasNone: On Hold
          githubToken: ${{ secrets.GITHUB_TOKEN }}
